import type { BalanceConfig } from '@reino/game-core';

export const defaultGameBalance: BalanceConfig = {
  playerMaxHp: 100,
  enemyMaxHp: 100,
  missionTarget: 5,
  baseCorrectDamage: 18,
  comboCorrectDamage: 22,
  comboThreshold: 3,
  wrongAnswerDamage: 20,
  shieldWrongAnswerDamage: 5,
  timeoutDamage: 10,
  scrollDamage: 25,
  focusMax: 100,
  focusStart: 0,
  focusCorrectGain: 5,
  focusComboGain: 2,
  focusMissionBonus: 10,
  focusDecayDelaySeconds: 7,
  focusDecayIntervalSeconds: 1.5,
  focusDecayPerSecond: 1,
  timedFocusDecayPerSecond: 1,
  focusCapByLevel: [30, 45, 60, 75, 100, 100],
  focusTimerBonusSeconds: 0,
};
